image: python:3.12

workflow:
  rules:
    - if: |
        $CI_COMMIT_TAG ||
        $CI_COMMIT_BRANCH == "main"

stages:
  - lint
  - deploy

lint-job:
  stage: lint
  before_script:
    - pip install ruff
  script:
    - ruff check .
  allow_failure: false

deploy-job:
  image: harbor.eds.aphp.fr/cohort360/kaniko:debug
  stage: deploy
  script:
    - export VERSION=$(python -c "from platform_registry.core.config import settings; print(settings.VERSION)")
    - mkdir -p /kaniko/.docker
    - |-
      KANIKOCFG="{ "\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${BOT_NAME}\",\"password\":\"${BOT_TOKEN}\"}}" }"
      echo "${KANIKOCFG}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${VERSION}"
  only:
    - tags
    - main