services:
  db:
    image: postgres:15.7
    container_name: registry_db
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    networks:
      custom:
        ipv4_address: 172.11.0.3
    env_file:
      - .docker.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: registry_api
    restart: always
    depends_on:
      - db
    networks:
      custom:
        ipv4_address: 172.11.0.4
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    environment:
      - DB_HOST=registry_db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  app-db-data:

networks:
  custom:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16
          gateway: 172.11.0.1
