services:
  db:
    image: postgres:14
    container_name: pg_db
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .docker.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: registry_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    environment:
      - DB_HOST=pg_db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_TOKEN_EXPIRE_MINUTES=${JWT_TOKEN_EXPIRE_MINUTES}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - ACCESS_KEY_LIFESPAN_DAYS=${ACCESS_KEY_LIFESPAN_DAYS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./coverage:/app/coverage

volumes:
  app-db-data:
