"""rename m2m rels

Revision ID: 47a898c72185
Revises: f1d631fe4c9c
Create Date: 2024-09-10 14:49:13.304054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47a898c72185'
down_revision: Union[str, None] = 'f1d631fe4c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_entity_rel',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_entity_rel_entity_id'), 'project_entity_rel', ['entity_id'], unique=False)
    op.create_index(op.f('ix_project_entity_rel_id'), 'project_entity_rel', ['id'], unique=True)
    op.create_index(op.f('ix_project_entity_rel_project_id'), 'project_entity_rel', ['project_id'], unique=False)
    op.create_table('project_regulatory_framework_rel',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('regulatory_framework_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['regulatory_framework_id'], ['regulatory_framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_regulatory_framework_rel_id'), 'project_regulatory_framework_rel', ['id'], unique=True)
    op.create_index(op.f('ix_project_regulatory_framework_rel_project_id'), 'project_regulatory_framework_rel', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_regulatory_framework_rel_regulatory_framework_id'), 'project_regulatory_framework_rel', ['regulatory_framework_id'], unique=False)
    op.create_table('project_user_rel',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_user_rel_id'), 'project_user_rel', ['id'], unique=True)
    op.create_index(op.f('ix_project_user_rel_project_id'), 'project_user_rel', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_user_rel_user_id'), 'project_user_rel', ['user_id'], unique=False)
    op.drop_index('ix_projects_regulatory_frameworks_rel_id', table_name='projects_regulatory_frameworks_rel')
    op.drop_index('ix_projects_regulatory_frameworks_rel_project_id', table_name='projects_regulatory_frameworks_rel')
    op.drop_index('ix_projects_regulatory_frameworks_rel_regulatory_framework_id', table_name='projects_regulatory_frameworks_rel')
    op.drop_table('projects_regulatory_frameworks_rel')
    op.drop_index('ix_project_membership_rel_id', table_name='project_membership_rel')
    op.drop_index('ix_project_membership_rel_project_id', table_name='project_membership_rel')
    op.drop_index('ix_project_membership_rel_user_id', table_name='project_membership_rel')
    op.drop_table('project_membership_rel')
    op.drop_column('role', 'manage_projects_membership')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('manage_projects_membership', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('project_membership_rel',
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('functional_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name='project_membership_rel_entity_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_membership_rel_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='project_membership_rel_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_membership_rel_pkey')
    )
    op.create_index('ix_project_membership_rel_user_id', 'project_membership_rel', ['user_id'], unique=False)
    op.create_index('ix_project_membership_rel_project_id', 'project_membership_rel', ['project_id'], unique=False)
    op.create_index('ix_project_membership_rel_id', 'project_membership_rel', ['id'], unique=True)
    op.create_table('projects_regulatory_frameworks_rel',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('regulatory_framework_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='projects_regulatory_frameworks_rel_project_id_fkey'),
    sa.ForeignKeyConstraint(['regulatory_framework_id'], ['regulatory_framework.id'], name='projects_regulatory_frameworks_rel_regulatory_framework_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='projects_regulatory_frameworks_rel_pkey')
    )
    op.create_index('ix_projects_regulatory_frameworks_rel_regulatory_framework_id', 'projects_regulatory_frameworks_rel', ['regulatory_framework_id'], unique=False)
    op.create_index('ix_projects_regulatory_frameworks_rel_project_id', 'projects_regulatory_frameworks_rel', ['project_id'], unique=False)
    op.create_index('ix_projects_regulatory_frameworks_rel_id', 'projects_regulatory_frameworks_rel', ['id'], unique=True)
    op.drop_index(op.f('ix_project_user_rel_user_id'), table_name='project_user_rel')
    op.drop_index(op.f('ix_project_user_rel_project_id'), table_name='project_user_rel')
    op.drop_index(op.f('ix_project_user_rel_id'), table_name='project_user_rel')
    op.drop_table('project_user_rel')
    op.drop_index(op.f('ix_project_regulatory_framework_rel_regulatory_framework_id'), table_name='project_regulatory_framework_rel')
    op.drop_index(op.f('ix_project_regulatory_framework_rel_project_id'), table_name='project_regulatory_framework_rel')
    op.drop_index(op.f('ix_project_regulatory_framework_rel_id'), table_name='project_regulatory_framework_rel')
    op.drop_table('project_regulatory_framework_rel')
    op.drop_index(op.f('ix_project_entity_rel_project_id'), table_name='project_entity_rel')
    op.drop_index(op.f('ix_project_entity_rel_id'), table_name='project_entity_rel')
    op.drop_index(op.f('ix_project_entity_rel_entity_id'), table_name='project_entity_rel')
    op.drop_table('project_entity_rel')
    # ### end Alembic commands ###
