"""alter fields

Revision ID: f010c0079052
Revises: e3e0a0fa51c8
Create Date: 2024-09-03 10:05:24.179648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f010c0079052'
down_revision: Union[str, None] = 'e3e0a0fa51c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms_shared_projects_rel', 'read')
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_index('ix_user_lastname', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=False)
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    op.add_column('platforms_shared_projects_rel', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
