"""access keys abel

Revision ID: f1d631fe4c9c
Revises: f010c0079052
Create Date: 2024-09-06 18:07:59.917457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d631fe4c9c'
down_revision: Union[str, None] = 'f010c0079052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_key', 'name', new_column_name='label')
    op.drop_index('ix_access_key_name', table_name='access_key')
    op.create_index(op.f('ix_access_key_label'), 'access_key', ['label'], unique=True)
    op.alter_column('platforms_shared_projects_rel', 'write', new_column_name='readonly')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platforms_shared_projects_rel', 'readonly', new_column_name='write')
    op.alter_column('access_key', 'label', new_column_name='name')
    op.drop_index(op.f('ix_access_key_label'), table_name='access_key')
    op.create_index('ix_access_key_name', 'access_key', ['name'], unique=True)
    # ### end Alembic commands ###
