"""first migration, create tables

Revision ID: 60edd895af44
Revises: 
Create Date: 2024-07-24 15:49:07.636312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60edd895af44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_type_id'), 'entity_type', ['id'], unique=True)
    op.create_index(op.f('ix_entity_type_name'), 'entity_type', ['name'], unique=False)
    op.create_table('platform',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_id'), 'platform', ['id'], unique=True)
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=True)
    op.create_table('project',
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=True)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('regulatory_framework',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_framework_id'), 'regulatory_framework', ['id'], unique=True)
    op.create_index(op.f('ix_regulatory_framework_name'), 'regulatory_framework', ['name'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('user',
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('entity',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('entity_type_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_id'), 'entity', ['id'], unique=True)
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=False)
    op.create_table('platform_shared_projects',
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_shared_projects_id'), 'platform_shared_projects', ['id'], unique=True)
    op.create_index(op.f('ix_platform_shared_projects_platform_id'), 'platform_shared_projects', ['platform_id'], unique=False)
    op.create_index(op.f('ix_platform_shared_projects_project_id'), 'platform_shared_projects', ['project_id'], unique=False)
    op.create_table('project_regulatory_framework',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('regulatory_framework_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['regulatory_framework_id'], ['regulatory_framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_regulatory_framework_id'), 'project_regulatory_framework', ['id'], unique=True)
    op.create_index(op.f('ix_project_regulatory_framework_project_id'), 'project_regulatory_framework', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_regulatory_framework_regulatory_framework_id'), 'project_regulatory_framework', ['regulatory_framework_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('project_membership',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('functional_role', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_membership_id'), 'project_membership', ['id'], unique=True)
    op.create_index(op.f('ix_project_membership_project_id'), 'project_membership', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_membership_user_id'), 'project_membership', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_membership_user_id'), table_name='project_membership')
    op.drop_index(op.f('ix_project_membership_project_id'), table_name='project_membership')
    op.drop_index(op.f('ix_project_membership_id'), table_name='project_membership')
    op.drop_table('project_membership')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_project_regulatory_framework_regulatory_framework_id'), table_name='project_regulatory_framework')
    op.drop_index(op.f('ix_project_regulatory_framework_project_id'), table_name='project_regulatory_framework')
    op.drop_index(op.f('ix_project_regulatory_framework_id'), table_name='project_regulatory_framework')
    op.drop_table('project_regulatory_framework')
    op.drop_index(op.f('ix_platform_shared_projects_project_id'), table_name='platform_shared_projects')
    op.drop_index(op.f('ix_platform_shared_projects_platform_id'), table_name='platform_shared_projects')
    op.drop_index(op.f('ix_platform_shared_projects_id'), table_name='platform_shared_projects')
    op.drop_table('platform_shared_projects')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_id'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_regulatory_framework_name'), table_name='regulatory_framework')
    op.drop_index(op.f('ix_regulatory_framework_id'), table_name='regulatory_framework')
    op.drop_table('regulatory_framework')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_index(op.f('ix_platform_id'), table_name='platform')
    op.drop_table('platform')
    op.drop_index(op.f('ix_entity_type_name'), table_name='entity_type')
    op.drop_index(op.f('ix_entity_type_id'), table_name='entity_type')
    op.drop_table('entity_type')
    # ### end Alembic commands ###
